name: Join AIFrontiersLab GitHub Org
description: Request an invite to the AIFrontiersLab organization
title: "Hello AIFrontier, Please fill in the GitHub username field below and click the Create button to submit your request."
labels: ["org-invite"]
body:
  - type: input
    id: github
    attributes:
      label: GitHub username
      description: Your GitHub handle (e.g., octocat)
      placeholder: octocat
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: What do you want to do?
      options:
        - Contribute code
        - Documentation
        - Research / papers
        - Product / design
        - Community / events
    validations:
      required: true
